### ISSUE TITLE
DeepLab version

### ISSUE THREAD

**Issue by fawadahm** [hiwad-aziz/kitti_deeplab#1]
Hi, thank you for the great work. Could you please tell us which DeepLab version have you fined tuned that is available with this repo?

**Comment by abenbihi** [comment]
If you mean the architecture name, it is xception65. I found it in the graph summary.

**Comment by hiwad-aziz** [comment]
Hi, first of all, very sorry for the late reply. The DeepLab version that I used here is DeepLabv3+.
